// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class DialogueTable
{
	public class Row
	{
		public string Key;
		public string FR;
		public string AN;
		public string ES;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.Key = grid[i][0];
			row.FR = grid[i][1];
			row.AN = grid[i][2];
			row.ES = grid[i][3];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_Key(string find)
	{
		return rowList.Find(x => x.Key == find);
	}
	public List<Row> FindAll_Key(string find)
	{
		return rowList.FindAll(x => x.Key == find);
	}
	public Row Find_FR(string find)
	{
		return rowList.Find(x => x.FR == find);
	}
	public List<Row> FindAll_FR(string find)
	{
		return rowList.FindAll(x => x.FR == find);
	}
	public Row Find_AN(string find)
	{
		return rowList.Find(x => x.AN == find);
	}
	public List<Row> FindAll_AN(string find)
	{
		return rowList.FindAll(x => x.AN == find);
	}
	public Row Find_ES(string find)
	{
		return rowList.Find(x => x.ES == find);
	}
	public List<Row> FindAll_ES(string find)
	{
		return rowList.FindAll(x => x.ES == find);
	}

}